# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 15:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171001_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energia',
            name='off',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[023]\\d:[0-5]\\d')]),
        ),
        migrations.AlterField(
            model_name='energia',
            name='on',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[012]\\d:[0-5]\\d')]),
        ),
        migrations.AlterField(
            model_name='predio',
            name='off',
            field=models.CharField(default='09:00', max_length=5, validators=[django.core.validators.RegexValidator('^[023]\\d:[0-5]\\d')]),
        ),
        migrations.AlterField(
            model_name='predio',
            name='on',
            field=models.CharField(default='08:00', max_length=5, validators=[django.core.validators.RegexValidator('^[012]\\d:[0-5]\\d')]),
        ),
    ]
