# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171001_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energia',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
