# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 15:54
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Energia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[012]\\d:[0-5]\\d')])),
                ('off', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[023]\\d:[0-5]\\d')])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('on', models.CharField(default='08:00', max_length=5, validators=[django.core.validators.RegexValidator('^[012]\\d:[0-5]\\d')])),
                ('off', models.CharField(default='22:00', max_length=5, validators=[django.core.validators.RegexValidator('^[023]\\d:[0-5]\\d')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='energia',
            name='predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Predio'),
        ),
    ]
