# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energia',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='energia',
            name='predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predio', to='blog.Predio'),
        ),
    ]
