# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171001_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energia',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='energia',
            name='off',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='energia',
            name='on',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='predio',
            name='off',
            field=models.TimeField(default='22:00'),
        ),
        migrations.AlterField(
            model_name='predio',
            name='on',
            field=models.TimeField(default='08:00'),
        ),
    ]
