# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171001_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='predio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predios', to='blog.Predio'),
        ),
    ]
